### ISSUE TITLE
Strange distortion/artifacts

### ISSUE THREAD

**Issue by SystemZ** [discordapp/lilliput#10]
Hi, this lib is the best for generating thumbnails that I tested so far.
Thanks for the great job! :)

Unfortunately I have few files that give strange results.
Probably it's my fault (file may be broken somehow) but in players it looks ok.
Maybe it's worth to look at it?

I tried turning on and off `NormalizeOrientation` and used all 3 `ResizeMethod` options in my code but that doesn't have any effect on this. As I tested - FFmpeg gets first frame correctly.

My setup:
Ubuntu Desktop 16.04 64bit
go version go1.9.2 linux/amd64

Steps to reproduce:
1. Clone repo with commit c2b38847094c248c1dad51293c60bdbb9397a2a1 (latest when I'm writing this)
2. Get example .webm file to reproduce and unzip it [0d2cfdb1b7e04d66f4e4bf712932a03591696bbf515eb03d4a1a0663b97637d0.webm.zip](https://github.com/SystemZ/gotag/files/1514352/0d2cfdb1b7e04d66f4e4bf712932a03591696bbf515eb03d4a1a0663b97637d0.webm.zip)
```plain
wget https://github.com/SystemZ/gotag/files/1514352/0d2cfdb1b7e04d66f4e4bf712932a03591696bbf515eb03d4a1a0663b97637d0.webm.zip
```
3. Use examples/main.go to convert .webm to .png (or .jpg)
```plain
go run main.go -input test.webm -output test.png
```
4. Thumbnail is not looking correctly

![zxejh9d6cng5jl4c](https://user-images.githubusercontent.com/1836094/33381704-050c23b6-d51f-11e7-904b-16b90fa739c5.png)

**Comment by brian-armstrong-discord** [comment]
Hi @SystemZ 

Sorry for the considerable delay!

I think I found the cause of this. It seems https://github.com/discordapp/lilliput/pull/14 fixes things for your example video. We'll merge this soon. Please let us know if you find any other distorted images after this lands.

Thanks!

**Comment by SystemZ** [comment]
So far on few videos I see it resolved.
Thanks! 😃 

I'll reopen if I find buggy video again.

**Comment by brian-armstrong-discord** [comment]
@SystemZ By the way, I came up with an even better fix for this and have just merged it. I had a misunderstanding about how libavcodec works, but now I'm pretty confident I've got it.

**Comment by SystemZ** [comment]
@brian-armstrong-discord I tested 01c93dea837a1c6c49ef8be4c474773b54f22171 with my app, works great, thanks for great work! 👍
