### ISSUE TITLE
data races question

### ISSUE THREAD

**Issue by mymtw** [discordapp/lilliput#11]
Hi,
Is such global variables will be secure, if you will run e.g. tests in parallel, for code that using `lilliput` with `-race` flag?
https://github.com/discordapp/lilliput/blob/master/opencv.go#L25
Cuz I'm afraid here is race condition
thx.

**Comment by brian-armstrong-discord** [comment]
@mymtw Can you expand on what you mean? The values you pointed to are constants. They're used as flags to indicate the attribute being changed -- think of them as the key to the actual quality's value. You can see how they're used in the example https://github.com/discordapp/lilliput/blob/master/examples/main.go#L14

**Comment by mymtw** [comment]
you can see here - https://golang.org/doc/articles/race_detector.html#Unprotected_global_variable

**Comment by brian-armstrong-discord** [comment]
Can you link to the tests you're running that give this error?

**Comment by brian-armstrong-discord** [comment]
I made those vars consts, though I don't believe there was an error here. Those values aren't meant to be changed, so if user code does that, it's an error. I think the names might be sort of misleading though, and I'm hoping making them consts clarifies that.
