### ISSUE TITLE
can you share some bbs discus group or telegram channel for this repo ?

### ISSUE THREAD

**Issue by joostshao** [discordapp/lilliput#16]
can you share some bbs discus group or telegram channel for this repo ?

**Comment by joostshao** [comment]
make[2]: Leaving directory '/home/sjt/work/go/src/github.com/discordapp/lilliput/deps/build/giflib'
make[1]: Leaving directory '/home/sjt/work/go/src/github.com/discordapp/lilliput/deps/build/giflib'
build-deps-linux.sh:行79: /home/sjt/work/go/src/github.com/discordapp/lilliput/deps/0001-export-exif-orientation.patch: 没有那个文件或目录

**Comment by brian-armstrong-discord** [comment]
Sorry about that. Should be fixed in the latest master.
