### ISSUE TITLE
New release build

### ISSUE THREAD

**Issue by theRoughCode** [discordapp/lilliput#37]
Hi lilliput team!

I was wondering when the next release version will be released?  Currently, if I use `go get...`, my project works, but if I use `dep ensure`, it fails due to a C++ issue.  I believe this was solved in one of the commits that got merged after v1.1.  Could you release an update release to solve this?

Thanks!

**Comment by theRoughCode** [comment]
Hey Brian, thanks for the quick reply.  It works now, but there's another error when trying to build it in docker.  I tried to run `build-deps-osx.sh` but it's giving me this error:
```
avcodec.cpp:7:32: fatal error: libavcodec/avcodec.h: No such file or directory
 #include <libavcodec/avcodec.h>
                                ^
compilation terminated.
```

Any thoughts?

**Comment by brian-armstrong-discord** [comment]
Just to be clear, you should only need to build deps if you're changing something about the C dependencies. Otherwise, the ones that are built in should just work (lilliput has been set up specifically to avoid needing to build any C/C++ save for the tiny bit of CGo wrapper).

Can you confirm the contents of `lilliput/deps/osx/include` inside the container? Just a basic `ls` will do.

**Comment by brian-armstrong-discord** [comment]
Also, I'm a little confused. That error looks related to building the wrapper itself, not deps.

**Comment by theRoughCode** [comment]
Output of `ls`:
```
bzlib.h		jpeglib.h	libavutil	opencv2		webp
gif_lib.h	libavcodec	libpng16	png.h		zconf.h
jconfig.h	libavdevice	libswresample	pngconf.h	zlib.h
jerror.h	libavfilter	libswscale	pnglibconf.h
jmorecfg.h	libavformat	opencv		turbojpeg.h
```

So, firstly, docker runs linux, so I should've run `build-deps-linux.sh`.  Secondly, I believe the error is occurring due to `SRCDIR` being incorrect in docker?  i.e. `#cgo linux CFLAGS: -I${SRCDIR}/deps/linux/include` in `avcodec.go`

**Comment by brian-armstrong-discord** [comment]
Is it possible your path has spaces in it? `SRCDIR` is set by the Go compiler. But apparently it doesn't gracefully handle paths with various non-alphanumeric characters https://github.com/golang/go/issues/11868

**Comment by theRoughCode** [comment]
Thanks for being so active in helping me try to solve this!  Hmm... I didn't get the error that was showing in that issue.  And I don't have any spaces in my path.   🤔

**Comment by theRoughCode** [comment]
Oh interesting, so `dep ensure` does not actually download the necessary files in `deps/linux/include`.  Do you know why?

**Comment by brian-armstrong-discord** [comment]
That looks really broken. I don't know what's going on with it, but I also don't know what `dep ensure` is. Might be worth clearing out the directory and retrying?

**Comment by theRoughCode** [comment]
Oh, I found out the solution.  Had to allow `unused-packages` https://github.com/golang/dep/issues/1731.  Thanks for all the help Brian, and would love to help contribute to this project or even intern at Discord to work on cool projects like this in the future!
