### ISSUE TITLE
Build failed: lilliput don't work with go mod

### ISSUE THREAD

**Issue by godsnuts** [discordapp/lilliput#55]
this is an error. when I use go mod and try to compile.
```
# github.com/discordapp/lilliput
/usr/bin/ld: cannot find -lpng
/usr/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
```

**Comment by brian-armstrong-discord** [comment]
Hello, sorry to hear this doesn't work.

It looks like the issue is described here https://github.com/golang/go/issues/26366

Feel free to give your feedback to the Go maintainers about this issue.

**Comment by EmpireJones** [comment]
I was able to work around this by replacing the symbolic links from libpng.[l]a -> libpng16.[l]a with copies of the files.

@brian-armstrong-discord  - Any chance this could get into master (or removing the need for the link existing), to allow for projects which use go mod functionality?
