### ISSUE TITLE
How to compile and deploy a go binary using lilliput

### ISSUE THREAD

**Issue by thebedroomprogrammer** [discordapp/lilliput#58]
So I am working on an image resizer that runs on serverless on a lambda function. 
When I run my go server on local machine using go run *.go the code works fine. But when I build a binary from the code I get errors related to see that "usr/bin/ld -lpng" not found

I am sure that lilliput uses some c bindings inorder to work with the image transformations but I am not able to get the way to properly build a single binary which I could deploy to my lambda function.

**Comment by brian-armstrong-discord** [comment]
Hello,

It sounds like you might be using go mod which from what I can tell doesn't work entirely. There may be a workaround here https://github.com/discordapp/lilliput/issues/55#issuecomment-480103097
