### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by qrpike** [discordapp/lilliput#59]
I keep getting issues pertaining to the C libraries when trying to build this as part of my project. 

I have used both go mod and glide as dependency management tools.

```

# github.com/discordapp/lilliput
--
208 | /usr/bin/ld: cannot find -lpng
209 | /usr/bin/ld: cannot find -lpng
210 | collect2: error: ld returned 1 exit status

```

Build command:
```
CGO_ENABLED=1 GOOS=linux go build -a -tags netgo -ldflags '-w' .
```

**Comment by brian-armstrong-discord** [comment]
Hello,

I have no experience with go mod but it sounds like it is still beta software. You might find a workaround here https://github.com/discordapp/lilliput/issues/55#issuecomment-480103097
