### ISSUE TITLE
Libraries in deps/linux/lib/ can not be used when making a shared object

### ISSUE THREAD

**Issue by mapx** [discordapp/lilliput#6]
Numerous errors arise when building the example `main.go`, such as:

```
/usr/bin/ld: src/github.com/discordapp/lilliput/deps/linux/lib/libavcodec.a(bsf.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: src/github.com/discordapp/lilliput/deps/linux/lib/libavcodec.a(vp8dsp_init.o): relocation R_X86_64_32S against hidden symbol `ff_put_vp8_pixels8_mmx' can not be used when making a shared object
```
Tested environments:
* go1.7.4 linux/amd64 + gcc version 6.3.0 20170516 (Debian 6.3.0-18)
* go1.9.2 linux/amd64 + gcc version 6.4.0 (Gentoo Hardened 6.4.0 p1.1)

Thanks.

**Comment by brian-armstrong-discord** [comment]
I mentioned this on #8 already, but I believe the fix is going to look more like https://blog.hashbangbash.com/2014/04/linking-golang-statically/. Basically, we should try to get Go to build this statically here. We could also try rebuilding the libs with -fPIC if static turns out to be infeasible.

**Comment by Gargron** [comment]
I thought it'd be cool to wrap lilliput in ruby-ffi but stuck on this problem.

**Comment by brian-armstrong-discord** [comment]
The fix for this most likely looks like recompiling all the libs with -fPIC. I think it's mostly just a matter of poking at each build step and getting -fPIC enabled.

**Comment by brian-armstrong-discord** [comment]
@lookapanda @Gargron @mapx I believe this is fixed by #20. I tested and the library now seems to build on Debian as well as Ubuntu. If you can each test in your respective contexts and let me know of any new issues, that'd be very helpful

**Comment by lookapanda** [comment]
@brian-armstrong-discord Hello.
![image](https://user-images.githubusercontent.com/770632/36631764-e2d3b4d2-197d-11e8-82e4-7ea7c5345ac8.png)

I now get this when only trying to add it as a dependency on Windows. It doesn't happen on Mac. I will post another post later when trying to actually build it on GitLab CI.

**Comment by brian-armstrong-discord** [comment]
@lookapanda You'll want to upgrade the version of Go you're using. See also #21

**Comment by brian-armstrong-discord** [comment]
Aside from that, it's fairly unlikely this will work in Windows unless you're using the Linux subsystem, and even then I'm not entirely sure how well that'll work. The README does call out this limitation. A compatible build for Windows might be possible, but will likely require a lot of effort.

**Comment by brian-armstrong-discord** [comment]
I'm closing this since I believe this is fixed. If this issue comes up for anyone again, feel free to re-open.
