### ISSUE TITLE
Missing 0001-export-exif-orientation.patch

### ISSUE THREAD

**Issue by mapx** [discordapp/lilliput#7]
https://github.com/discordapp/lilliput/blob/c2b38847094c248c1dad51293c60bdbb9397a2a1/deps/build-deps-linux.sh#L79 requires file `0001-export-exif-orientation.patch` which does not exist any more.

`$BASEDIR` should be `$SRCDIR`. There are other stuff in this directory that could be improved.

**Comment by brian-armstrong-discord** [comment]
Fixed. Thanks for the report.
